-- MIGRACION PARA EL REDISEÑO DE LEADS
-- Ejecuta esto en el editor SQL de Supabase

-- Campos base y compartidos
ALTER TABLE leads ADD COLUMN IF NOT EXISTS lead_type TEXT DEFAULT 'prospecto';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS preferred_channel TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS language TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS current_city TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS campaign TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS origin_property TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS entry_date DATE DEFAULT CURRENT_DATE;

-- Prospecto (Demanda)
ALTER TABLE leads ADD COLUMN IF NOT EXISTS use_type TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS property_types TEXT[]; 
ALTER TABLE leads ADD COLUMN IF NOT EXISTS interest_zones TEXT[];
ALTER TABLE leads ADD COLUMN IF NOT EXISTS min_budget DECIMAL(15,2);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS max_budget DECIMAL(15,2);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS bedrooms TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS bathrooms TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS parkings TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS amenities TEXT[];
ALTER TABLE leads ADD COLUMN IF NOT EXISTS payment_method TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS credit_preapproved BOOLEAN DEFAULT false;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS bank TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS down_payment DECIMAL(15,2);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS urgency_level TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS target_date DATE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS urgency_reason TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS interest_level INT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS closure_probability INT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS sees_other_agencies BOOLEAN DEFAULT false;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS follow_up_channel TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS internal_note TEXT;

-- Propietario (Oferta)
ALTER TABLE leads ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS area TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS m2_built DECIMAL(10,2);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS expected_price DECIMAL(15,2);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS min_price_acceptable DECIMAL(15,2);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS exclusivity BOOLEAN DEFAULT false;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS time_to_close TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS legal_free_of_charges BOOLEAN DEFAULT false;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS legal_deed_available BOOLEAN DEFAULT false;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS legal_mortgage_existing BOOLEAN DEFAULT false;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS motivation_reason TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS owner_urgency_level TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS commission_agreed DECIMAL(5,2);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS publish_date DATE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS attachment_urls TEXT[];
