-- Migration: WhatsApp Integration Schema
-- Description: Creates tables for tracking sessions, conversations, and messages via WAHA.

-- 1. WhatsApp Sessions
CREATE TABLE IF NOT EXISTS public.whatsapp_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT UNIQUE NOT NULL, -- e.g. "default"
    phone_number TEXT,
    status TEXT CHECK (status IN ('connected', 'disconnected', 'pairing')) DEFAULT 'disconnected',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. WhatsApp Conversations
CREATE TABLE IF NOT EXISTS public.whatsapp_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number TEXT UNIQUE NOT NULL,
    lead_id BIGINT REFERENCES public.leads(id) ON DELETE SET NULL,
    last_message_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. WhatsApp Messages
CREATE TABLE IF NOT EXISTS public.whatsapp_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT REFERENCES public.whatsapp_conversations(id) ON DELETE CASCADE,
    direction TEXT CHECK (direction IN ('incoming', 'outgoing')) NOT NULL,
    message_type TEXT CHECK (message_type IN ('text', 'image', 'file', 'video')) DEFAULT 'text',
    content TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    waha_message_id TEXT -- External ID from WAHA
);

-- Enable RLS
ALTER TABLE public.whatsapp_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_messages ENABLE ROW LEVEL SECURITY;

-- Note: Ensure permissions are set for the anon/authenticated rolls as per project policy.
