-- Consolidation of WhatsApp Module for Production Ready State
-- This migration includes tables, indexes, RLS policies, and missing columns.

-- 1. WhatsApp Conversations (Base Table)
CREATE TABLE IF NOT EXISTS public.whatsapp_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number TEXT UNIQUE NOT NULL,
    lead_id BIGINT REFERENCES public.leads(id) ON DELETE SET NULL,
    last_message_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_message_content TEXT,
    contact_name TEXT,
    unread_count INTEGER DEFAULT 0,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. WhatsApp Messages
CREATE TABLE IF NOT EXISTS public.whatsapp_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT REFERENCES public.whatsapp_conversations(id) ON DELETE CASCADE,
    direction TEXT CHECK (direction IN ('incoming', 'outgoing')) NOT NULL,
    message_type TEXT CHECK (message_type IN ('text', 'image', 'file', 'video')) DEFAULT 'text',
    content TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    waha_message_id TEXT UNIQUE,
    status TEXT DEFAULT 'sent'
);

-- 3. WhatsApp Tags
CREATE TABLE IF NOT EXISTS public.whatsapp_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    color TEXT DEFAULT '#000000',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. WhatsApp Chat Tags (Relationship)
CREATE TABLE IF NOT EXISTS public.whatsapp_chat_tags (
    chat_id BIGINT REFERENCES public.whatsapp_conversations(id) ON DELETE CASCADE,
    tag_id BIGINT REFERENCES public.whatsapp_tags(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (chat_id, tag_id)
);

-- 5. WhatsApp Sessions (Internal state tracking)
CREATE TABLE IF NOT EXISTS public.whatsapp_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT UNIQUE NOT NULL, 
    phone_number TEXT,
    status TEXT CHECK (status IN ('connected', 'disconnected', 'pairing')) DEFAULT 'disconnected',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.whatsapp_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_chat_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_sessions ENABLE ROW LEVEL SECURITY;

-- RLS Policies (Simple authenticated access)
DO $$ 
BEGIN
    -- Conversations
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Authenticated users can manage conversations') THEN
        CREATE POLICY "Authenticated users can manage conversations" ON public.whatsapp_conversations
        FOR ALL USING (auth.role() = 'authenticated');
    END IF;

    -- Messages
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Authenticated users can manage messages') THEN
        CREATE POLICY "Authenticated users can manage messages" ON public.whatsapp_messages
        FOR ALL USING (auth.role() = 'authenticated');
    END IF;

    -- Tags
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Authenticated users can manage tags') THEN
        CREATE POLICY "Authenticated users can manage tags" ON public.whatsapp_tags
        FOR ALL USING (auth.role() = 'authenticated');
    END IF;

    -- Chat Tags
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Authenticated users can manage chat tags') THEN
        CREATE POLICY "Authenticated users can manage chat tags" ON public.whatsapp_chat_tags
        FOR ALL USING (auth.role() = 'authenticated');
    END IF;

    -- Sessions
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Authenticated users can manage sessions') THEN
        CREATE POLICY "Authenticated users can manage sessions" ON public.whatsapp_sessions
        FOR ALL USING (auth.role() = 'authenticated');
    END IF;
END $$;

-- 6. Performance Indexes
CREATE INDEX IF NOT EXISTS idx_whatsapp_conversations_last_message_at ON public.whatsapp_conversations(last_message_at DESC);
CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_conversation_id_timestamp ON public.whatsapp_messages(conversation_id, timestamp ASC);
CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_waha_id ON public.whatsapp_messages(waha_message_id);
CREATE INDEX IF NOT EXISTS idx_whatsapp_conversations_phone_number ON public.whatsapp_conversations(phone_number);
CREATE INDEX IF NOT EXISTS idx_whatsapp_chat_tags_chat_id ON public.whatsapp_chat_tags(chat_id);
