-- Create portal_credentials table
create table if not exists public.portal_credentials (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  portal_name text not null, -- 'zonaprop', 'argenprop', etc.
  username text not null,
  password text not null, -- Ideally encrypted, but for MVP we use plain with RLS
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, portal_name)
);

-- RLS
alter table public.portal_credentials enable row level security;

create policy "Users can manage their own credentials"
on public.portal_credentials
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
