-- Create Document Management System Schema

-- Enums
DO $$ BEGIN
    CREATE TYPE document_type AS ENUM ('boleto', 'reserva', 'contrato', 'señal', 'pdf_firmado', 'identidad', 'garantia', 'otro');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE document_status AS ENUM ('borrador', 'en_revision', 'firmado', 'vencido');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Documents Table
CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type document_type NOT NULL DEFAULT 'otro',
    status document_status NOT NULL DEFAULT 'borrador',
    storage_path TEXT NOT NULL, -- Pointing to the latest version in Storage
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id),
    is_deleted BOOLEAN DEFAULT FALSE
);

-- Polymorphic Relations Table
CREATE TABLE IF NOT EXISTS document_relations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT REFERENCES documents(id) ON DELETE CASCADE,
    entity_type TEXT NOT NULL CHECK (entity_type IN ('client', 'property', 'operation', 'rental')),
    entity_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Versioning Table
CREATE TABLE IF NOT EXISTS document_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT REFERENCES documents(id) ON DELETE CASCADE,
    storage_path TEXT NOT NULL,
    version_number INTEGER NOT NULL,
    change_description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_document_relations_entity ON document_relations(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_document_versions_doc_id ON document_versions(document_id);

-- RLS
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_relations ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_versions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view all documents" ON documents FOR SELECT TO authenticated USING (NOT is_deleted);
CREATE POLICY "Users can upload documents" ON documents FOR INSERT TO authenticated WITH CHECK (TRUE);
CREATE POLICY "Users can update documents" ON documents FOR UPDATE TO authenticated USING (TRUE);

CREATE POLICY "Users can view all relations" ON document_relations FOR SELECT TO authenticated USING (TRUE);
CREATE POLICY "Users can create relations" ON document_relations FOR INSERT TO authenticated WITH CHECK (TRUE);

CREATE POLICY "Users can view all versions" ON document_versions FOR SELECT TO authenticated USING (TRUE);
CREATE POLICY "Users can create versions" ON document_versions FOR INSERT TO authenticated WITH CHECK (TRUE);

-- Storage Bucket
INSERT INTO storage.buckets (id, name, public) 
VALUES ('documents', 'documents', false) 
ON CONFLICT (id) DO NOTHING;

-- Policies for storage
CREATE POLICY "Authenticated users can upload documents" 
ON storage.objects FOR INSERT TO authenticated 
WITH CHECK (bucket_id = 'documents');

CREATE POLICY "Authenticated users can read documents" 
ON storage.objects FOR SELECT TO authenticated 
USING (bucket_id = 'documents');

CREATE POLICY "Authenticated users can update documents" 
ON storage.objects FOR UPDATE TO authenticated 
USING (bucket_id = 'documents');

CREATE POLICY "Authenticated users can delete documents" 
ON storage.objects FOR DELETE TO authenticated 
USING (bucket_id = 'documents');
