-- Create calendar_events table
create table if not exists public.calendar_events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  location text,
  color text default 'blue',
  created_by uuid references auth.users(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Add RLS policies
alter table public.calendar_events enable row level security;

create policy "Users can read all events" on public.calendar_events for select using (true);
create policy "Users can insert their own events" on public.calendar_events for insert with check (auth.uid() = created_by);
create policy "Users can update their own events" on public.calendar_events for update using (auth.uid() = created_by);
create policy "Users can delete their own events" on public.calendar_events for delete using (auth.uid() = created_by);
