-- Create tags table
CREATE TABLE IF NOT EXISTS public.whatsapp_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    color TEXT DEFAULT '#000000',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create relationship table between chats and tags
CREATE TABLE IF NOT EXISTS public.whatsapp_chat_tags (
    chat_id BIGINT REFERENCES public.whatsapp_conversations(id) ON DELETE CASCADE,
    tag_id BIGINT REFERENCES public.whatsapp_tags(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (chat_id, tag_id)
);

-- Enable RLS
ALTER TABLE public.whatsapp_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_chat_tags ENABLE ROW LEVEL SECURITY;

-- Create policies for tags (open access for authenticated users for now)
CREATE POLICY "Enable read access for all users" ON public.whatsapp_tags FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.whatsapp_tags FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update for authenticated users only" ON public.whatsapp_tags FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Enable delete for authenticated users only" ON public.whatsapp_tags FOR DELETE USING (auth.role() = 'authenticated');

-- Create policies for chat_tags
CREATE POLICY "Enable read access for all users" ON public.whatsapp_chat_tags FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.whatsapp_chat_tags FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable delete for authenticated users only" ON public.whatsapp_chat_tags FOR DELETE USING (auth.role() = 'authenticated');
