-- Force Fix for portal_credentials
-- This ensures the table is exactly what we need for the unauthenticated '1' ID bypass.

-- 1. Drop and recreate to be absolutely sure of the schema
drop table if exists public.portal_credentials cascade;

create table public.portal_credentials (
  id bigint generated by default as identity primary key,
  user_id text not null, -- '1'
  portal_name text not null, -- 'zonaprop'
  username text not null,
  password text not null,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, portal_name)
);

-- 2. Disable RLS
alter table public.portal_credentials disable row level security;

-- 3. Grant access (just in case)
grant all on public.portal_credentials to anon;
grant all on public.portal_credentials to authenticated;
grant all on public.portal_credentials to service_role;
