-- Create client_proposals table
create table if not exists public.client_proposals (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  property_id bigint references public.properties(id) on delete set null,
  property_address text,
  status text check (status in ('Pendiente', 'Aceptada', 'Rechazada', 'En Negociación')) default 'Pendiente',
  type text check (type in ('Venta', 'Alquiler')) default 'Venta',
  price numeric,
  currency text default 'USD',
  notes text,
  sent_date timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Add RLS policies
alter table public.client_proposals enable row level security;

create policy "Enable read access for all users" on public.client_proposals for select using (true);
create policy "Enable insert for authenticated users" on public.client_proposals for insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users" on public.client_proposals for update using (auth.role() = 'authenticated');
create policy "Enable delete for authenticated users" on public.client_proposals for delete using (auth.role() = 'authenticated');
