-- Create property_price_history table
CREATE TABLE IF NOT EXISTS public.property_price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT REFERENCES public.properties(id) ON DELETE CASCADE,
    old_price NUMERIC,
    new_price NUMERIC,
    currency TEXT,
    changed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.property_price_history ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable read access for all users" ON public.property_price_history FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON public.property_price_history FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Index for performance
CREATE INDEX IF NOT EXISTS idx_property_price_history_property_id ON public.property_price_history(property_id);
CREATE INDEX IF NOT EXISTS idx_property_price_history_changed_at ON public.property_price_history(changed_at DESC);
