-- Add customer_status to clients table
ALTER TABLE public.clients 
ADD COLUMN IF NOT EXISTS customer_status TEXT DEFAULT 'Activo' CHECK (customer_status IN ('Activo', 'Dormido', 'Ex cliente', 'Inversor'));

-- Create client_status_history table
CREATE TABLE IF NOT EXISTS public.client_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT REFERENCES public.clients(id) ON DELETE CASCADE,
    old_status TEXT,
    new_status TEXT,
    changed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    changed_by UUID REFERENCES auth.users(id)
);

-- Enable RLS
ALTER TABLE public.client_status_history ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable read access for all users" ON public.client_status_history FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON public.client_status_history FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Indexes
CREATE INDEX IF NOT EXISTS idx_client_status_history_client_id ON public.client_status_history(client_id);
CREATE INDEX IF NOT EXISTS idx_client_status_history_changed_at ON public.client_status_history(changed_at DESC);
